/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_GeoHierarchySubSet */

#ifndef _Included_de_funroll_loops_oscar_nc_GeoHierarchySubSet
#define _Included_de_funroll_loops_oscar_nc_GeoHierarchySubSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_destroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    cellCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_cellCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    itemCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_itemCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    topK
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_topK
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    flaten
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_flaten
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
