/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_OsmCompleter */

#ifndef _Included_de_funroll_loops_oscar_nc_OsmCompleter
#define _Included_de_funroll_loops_oscar_nc_OsmCompleter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_OsmCompleter
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmCompleter_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmCompleter
 * Method:    destroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_funroll_1loops_oscar_nc_OsmCompleter_destroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmCompleter
 * Method:    setFilePrefix
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_OsmCompleter_setFilePrefix
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmCompleter
 * Method:    energize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_funroll_1loops_oscar_nc_OsmCompleter_energize
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmCompleter
 * Method:    store
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmCompleter_store
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
