/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_OsmKeyValueObjectStore */

#ifndef _Included_de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
#define _Included_de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_destroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_size
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    at
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_at
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
