/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_Helpers */

#ifndef _Included_de_funroll_loops_oscar_nc_Helpers
#define _Included_de_funroll_loops_oscar_nc_Helpers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_Helpers
 * Method:    setSlowTempFilePrefix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_Helpers_setSlowTempFilePrefix
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_funroll_loops_oscar_nc_Helpers
 * Method:    setFastTempFilePrefix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_Helpers_setFastTempFilePrefix
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
