/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_GeoHierarchySubSet */

#ifndef _Included_de_funroll_loops_oscar_nc_GeoHierarchySubSet
#define _Included_de_funroll_loops_oscar_nc_GeoHierarchySubSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    cellCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_cellCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    itemCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_itemCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    topK
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_topK
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_GeoHierarchySubSet
 * Method:    flaten
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_de_funroll_1loops_oscar_nc_GeoHierarchySubSet_flaten
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
