/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_OsmItem */

#ifndef _Included_de_funroll_loops_oscar_nc_OsmItem
#define _Included_de_funroll_loops_oscar_nc_OsmItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    id
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_id
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    ancestors
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_ancestors
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    isRegion
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_isRegion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    keyId
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_keyId
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    valueId
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_valueId
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    key
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_key
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    value
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_value
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
