/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_StringTable */

#ifndef _Included_de_funroll_loops_oscar_nc_StringTable
#define _Included_de_funroll_loops_oscar_nc_StringTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_StringTable
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_funroll_1loops_oscar_nc_StringTable_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_StringTable
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_StringTable_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_StringTable
 * Method:    size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_StringTable_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_StringTable
 * Method:    at
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_funroll_1loops_oscar_nc_StringTable_at
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
