/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_OsmKeyValueObjectStore */

#ifndef _Included_de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
#define _Included_de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    numberOfRegions
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_numberOfRegions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    at
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_at
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmKeyValueObjectStore
 * Method:    keyStringTable
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_funroll_1loops_oscar_nc_OsmKeyValueObjectStore_keyStringTable
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
