/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_funroll_loops_oscar_nc_OsmItem */

#ifndef _Included_de_funroll_loops_oscar_nc_OsmItem
#define _Included_de_funroll_loops_oscar_nc_OsmItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_create
  (JNIEnv *, jobject);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_destroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    id
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_id
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_size
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    key
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_key
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_funroll_loops_oscar_nc_OsmItem
 * Method:    value
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_funroll_1loops_oscar_nc_OsmItem_value
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
